# docker-compose.yml for My School Application

name: Deploy My School App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Construire l'image backend
      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my_school_backend:latest ./server_expressjs

      # 4️⃣ Construire l'image frontend (React + Nginx)
      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my_school_frontend:latest ./client_coreui_react

      # 5️⃣ Pousser les images sur Docker Hub
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my_school_backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my_school_frontend:latest

      # 6️⃣ Déployer sur le VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Créer le dossier du projet s'il n'existe pas
            mkdir -p /root/my_school
            cd /root/my_school

            # Créer le réseau proxy s'il n'existe pas
            docker network inspect proxy >/dev/null 2>&1 || docker network create proxy

            # Arrêter les anciens conteneurs si présents
            docker-compose down || true

            # Télécharger les dernières images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_school_backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_school_frontend:latest

            # Démarrer les conteneurs
            docker-compose up -d
