@baseUrl =http://localhost:4000
@superAdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJnaGFsYXNzIiwibGFzdE5hbWUiOm51bGwsImVtYWlsIjoiZ2hhbGFzc0BnbWFpbC5jb20iLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTc1ODYxMzc4NCwiZXhwIjoxNzU4NjM4OTg0fQ.IyAx9Yxa3GZw77NNw9fKIN3E4L0G66l31tbBlh-PO28
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJhbGkiLCJlbWFpbCI6ImFsaUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1ODUyNzE4OCwiZXhwIjoxNzU4NTUyMzg4fQ.Igzcrn27ys9s0gvIFtTIMom29EHJ_QBfk6eHJULnI7M

### LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"ghalass@gmail.com",
    "password":"gh@l@ss@dmin"
}

### CREATE USER (REQUIRE ADMIN OR SUPER_ADMIN)
POST {{baseUrl}}/auth/signup
Content-Type: application/json
Cookie: jwt={{superAdminToken}};

{
    "name":"user_for_test",
    "email":"user_for_test@email.com",
    "password":"123456"
}

### CREATE USER (REQUIRE ADMIN OR SUPER_ADMIN)
GET {{baseUrl}}/auth/me
Content-Type: application/json
Cookie: jwt={{superAdminToken}};
