@baseUrl =http://localhost:4000
@superAdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImdoYWxhc3MiLCJsYXN0TmFtZSI6bnVsbCwiZW1haWwiOiJnaGFsYXNzQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzYwNDM5MDMwLCJleHAiOjE3NjA0NjQyMzB9.BbxUp8RP6nVGs13OIueBvrW4WnqjSbw-Bc-DYO8EPCw
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJhbGkiLCJlbWFpbCI6ImFsaUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1ODUyNzE4OCwiZXhwIjoxNzU4NTUyMzg4fQ.Igzcrn27ys9s0gvIFtTIMom29EHJ_QBfk6eHJULnI7M

### LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"ghalass@gmail.com",
    "password":"gh@l@ss@dmin"
}

### CREATE USER (REQUIRE ADMIN OR SUPER_ADMIN)
POST {{baseUrl}}/auth/signup
Content-Type: application/json
Cookie: jwt={{superAdminToken}};

{
    "name":"user_for_test",
    "email":"user_for_test@email.com",
    "password":"123456"
}

### CREATE USER (REQUIRE ADMIN OR SUPER_ADMIN)
GET {{baseUrl}}/auth/me
Content-Type: application/json
Cookie: jwt={{superAdminToken}};
