@baseUrl =http://localhost:4000
@superAdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJnaGFsYXNzIiwiZW1haWwiOiJnaGFsYXNzQGdtYWlsLmNvbSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc1ODU0MjgzOCwiZXhwIjoxNzU4NTY4MDM4fQ.Dfq_LgKmtCCHMSGMvjwxThFfL_zJ4-sbULokvTxIduQ
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJhbGkiLCJsYXN0TmFtZSI6ImdoYWxhc3MiLCJlbWFpbCI6ImFsaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTc1OTU3NTQ0NywiZXhwIjoxNzU5NjAwNjQ3fQ.3IS61qtShCpdZt64YzZYSAAKEkJ0tEgVuMubM0fipfc
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJhbGkiLCJlbWFpbCI6ImFsaUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1ODUyNzE4OCwiZXhwIjoxNzU4NTUyMzg4fQ.Igzcrn27ys9s0gvIFtTIMom29EHJ_QBfk6eHJULnI7M

### USERS COUNT (REQUIRE AUTH)
GET {{baseUrl}}/dashboard
Cookie: jwt={{adminToken}};
